src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import IndexView, search, Login, Logout, Registration, ActivateUser, ProfileView, ProfileUpdateView

urlpatterns = [
                  path("", IndexView.as_view(), name="index"),
                  path("admin/", admin.site.urls),
                  path("search/", search, name="search"),
                  path("students/", include("students.urls")),
                  path("teachers/", include("teachers.urls")),
                  path("groups/", include("groups.urls")),
                  path("login/", Login.as_view(), name="login"),
                  path("logout/", Logout.as_view(), name="logout"),
                  path("registration/", Registration.as_view(), name="registration"),
                  path("activate/<str:uuid64>/<str:token>", ActivateUser.as_view(), name="activate_user"),
                  path("profile/<int:pk>", ProfileView.as_view(), name="profile"),
                  path("profile/<int:pk>/update", ProfileUpdateView.as_view(), name="profile-update"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/students/urls.py
from django.urls import path

from students.views import StudentListView, CreateStudentView, UpdateStudentView, DeleteStudentView

app_name = "students"

urlpatterns = [
    path("", StudentListView.as_view(), name="all_students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:pk>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:pk>/", DeleteStudentView.as_view(), name="delete_student"),
]

src/core/models.py
from datetime import datetime
from uuid import uuid4

from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator, MinLengthValidator
from django.db import models
from location_field.models.plain import PlainLocationField
from phonenumber_field.modelfields import PhoneNumberField

from utils import directory_path


class Person(models.Model):
    class Meta:
        abstract = True

    uuid = models.UUIDField(
        primary_key=True,
        editable=False,
        default=uuid4,
        unique=True,
        db_index=True,
    )
    avatar = models.ImageField(
        upload_to=directory_path,
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])],
        null=True,
        blank=True,
        default='')
    first_name = models.CharField(
        max_length=100,
        validators=[
            MinLengthValidator(2),
        ],
        default=''
    )
    last_name = models.CharField(
        max_length=100,
        validators=[
            MinLengthValidator(2),
        ],
        default=''
    )
    email = models.EmailField(max_length=100, default='')
    birth_date = models.DateField(null=True, default='')

    @property
    def get_photo_url(self):
        if self.avatar and hasattr(self.avatar, 'url'):
            return self.avatar.url
        else:
            return "/media/avatar.jpeg"

    def age(self):
        return datetime.now().year - self.birth_date.year


class Profile(models.Model):
    STUDENT = "Student"
    TEACHER = "Teacher"
    MENTOR = "Mentor"
    USER_TYPE_CHOICES = (
        (STUDENT, "Student"),
        (TEACHER, "Teacher"),
        (MENTOR, "Mentor"),
    )

    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    avatar = models.ImageField(
        upload_to=directory_path,
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])],
        null=True,
        blank=True,
        default="/media/avatar.jpeg"
    )
    birth_date = models.DateField(null=True, default='')
    phone_number = PhoneNumberField()
    facebook = models.URLField(max_length=255, null=True, blank=True, default='')
    github = models.URLField(max_length=255, null=True, blank=True, default='')
    city = models.CharField(max_length=255, null=True, blank=True, default='')
    location = PlainLocationField(based_fields=['city'], zoom=7, null=True, blank=True, default='')
    user_type = models.CharField(max_length=50, choices=USER_TYPE_CHOICES)

    @property
    def get_photo_url(self):
        if self.avatar and hasattr(self.avatar, 'url'):
            return self.avatar.url
        else:
            return "/media/avatar.jpeg"

    def __str__(self):
        return f"{self.user.username} {self.user.first_name} {self.user.last_name} {self.user.email}"

src/students/models.py
from django.core.validators import FileExtensionValidator
from django.db import models
from faker import Faker

from core.models import Person
from groups.models import Group
from utils import directory_path


class Student(Person):
    grade = models.PositiveSmallIntegerField(null=True, default=0)
    group = models.ForeignKey(
        to=Group,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    cv = models.FileField(
        upload_to=directory_path,
        validators=[FileExtensionValidator(allowed_extensions=['pdf'])],
        null=True,
        blank=True,
        default='')

    @classmethod
    def generate_students(cls, count):
        faker = Faker("uk_UA")

        for _ in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birth_date=faker.date_time_between(start_date="-30y", end_date="-18y"),
            )

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.email}"

src/core/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.forms import ModelForm, DateField, DateInput

from core.models import Profile


class PersonForm(ModelForm):
    birth_date = DateField(
        input_formats=["%d.%m.%Y", "%Y-%m-%d"],
        widget=DateInput(attrs={"placeholder": "dd.mm.yyyy", "type": "date"}),
    )

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email.lower():
            raise ValidationError("Yandex domain is forbidden in our country")

        return email

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean(self):
        cleaned_data = super().clean()

        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]

        if first_name == last_name:
            raise ValidationError("First name and last name can`t be equal")

        return cleaned_data


class RegistrationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ["first_name", "last_name", "username", "email", "password1", "password2"]


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ["avatar", "birth_date", "phone_number", "city", "facebook", "github", "user_type"]

src/students/forms.py
from core.forms import PersonForm
from students.models import Student


class StudentForm(PersonForm):
    class Meta:
        model = Student
        fields = "__all__"

src/core/views.py
from django.contrib.auth import login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.views.generic import TemplateView, CreateView, RedirectView, DetailView, UpdateView

from core.forms import RegistrationForm, ProfileForm
from core.models import Profile
from core.services.emails import send_registration_email
from core.utility.token_generator import TokenGenerator
from students.models import Student


class IndexView(TemplateView):
    template_name = "index.html"


class Registration(CreateView):
    template_name = "registration/create_user.html"
    form_class = RegistrationForm
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_active = False
        self.object.save()

        send_registration_email(
            self.request, user_instance=self.object
        )

        return super().form_valid(form)


class ActivateUser(RedirectView):
    url = reverse_lazy("index")

    def get(self, request, uuid64, token, *args, **kwargs):
        try:
            pk = force_str(urlsafe_base64_decode(uuid64))
            current_user = get_user_model().objects.get(pk=pk)
        except (get_user_model().DoesNotExist, TypeError, ValueError):
            return HttpResponse("Wrong data!")

        if current_user and TokenGenerator().check_token(current_user, token):
            current_user.is_active = True
            current_user.save()
            login(request, current_user)

            return super().get(request, *args, **kwargs)

        return HttpResponse("Wrong data!")


class Login(LoginView):
    next_page = reverse_lazy("index")


class Logout(LogoutView):
    next_page = reverse_lazy("login")


def search(request):
    if request.method == "POST":
        searched = request.POST["searched"]
        students = Student.objects.filter(Q(first_name__contains=searched) | Q(last_name__contains=searched))
        print(students)
        return render(request, template_name="search.html", context={"searched": searched, "students": students})

    return render(request, template_name="search.html", context={})


class ProfileView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = "profile.html"


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = "profile-update.html"
    login_url = "login"

    def get_success_url(self):
        return reverse_lazy('profile', kwargs={'pk': self.kwargs['pk']})

src/students/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from .forms import StudentForm
from .models import Student


class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    template_name = "students_list.html"
    login_url = "login"


class CreateStudentView(LoginRequiredMixin, CreateView):
    model = Student
    form_class = StudentForm
    template_name = "create.html"
    success_url = reverse_lazy("students:all_students")
    login_url = "login"


class UpdateStudentView(LoginRequiredMixin, UpdateView):
    model = Student
    form_class = StudentForm
    template_name = "update.html"
    success_url = reverse_lazy("students:all_students")
    login_url = "login"


class DeleteStudentView(LoginRequiredMixin, DeleteView):
    model = Student
    template_name = "delete.html"
    success_url = reverse_lazy("students:all_students")
    login_url = "login"

src/core/templates/students/students_list.html
{% extends "index.html" %}


{% block title %}
    Students
{% endblock %}

{% block content %}
    <div class="d-flex">
        <a type="button" class="btn btn-primary" href="{% url "students:create_student" %}">+Add new</a>
        <div class="form-outline">
            <form class="d-flex" method="POST" action="{% url "search" %}">

                {% csrf_token %}

                <input class="form-control me-1 ms-4" type="search" placeholder="Search" aria-label="Search"
                       name="searched">
                <button class="btn btn-outline-secondary" type="submit">Search</button>
            </form>
        </div>
    </div>
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">CV</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Birth date</th>
            <th scope="col">Age</th>
            <th scope="col">Grade</th>
            <th scope="col">Group</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
        {% for student in student_list %}
            <tr>
                <th><img src="{{ student.get_photo_url }}" alt="ava" width="32" height="32" class="rounded-circle"></th>
                <td>
                    {% if student.cv %}
                        <a href="{{ student.cv.url }}" target="_blank">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="red"
                                 class="bi bi-file-earmark-pdf" viewBox="0 0 16 16">
                                <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"/>
                                <path d="M4.603 14.087a.81.81 0 0 1-.438-.42c-.195-.388-.13-.776.08-1.102.198-.307.526-.568.897-.787a7.68 7.68 0 0 1 1.482-.645 19.697 19.697 0 0 0 1.062-2.227 7.269 7.269 0 0 1-.43-1.295c-.086-.4-.119-.796-.046-1.136.075-.354.274-.672.65-.823.192-.077.4-.12.602-.077a.7.7 0 0 1 .477.365c.088.164.12.356.127.538.007.188-.012.396-.047.614-.084.51-.27 1.134-.52 1.794a10.954 10.954 0 0 0 .98 1.686 5.753 5.753 0 0 1 1.334.05c.364.066.734.195.96.465.12.144.193.32.2.518.007.192-.047.382-.138.563a1.04 1.04 0 0 1-.354.416.856.856 0 0 1-.51.138c-.331-.014-.654-.196-.933-.417a5.712 5.712 0 0 1-.911-.95 11.651 11.651 0 0 0-1.997.406 11.307 11.307 0 0 1-1.02 1.51c-.292.35-.609.656-.927.787a.793.793 0 0 1-.58.029zm1.379-1.901c-.166.076-.32.156-.459.238-.328.194-.541.383-.647.547-.094.145-.096.25-.04.361.01.022.02.036.026.044a.266.266 0 0 0 .035-.012c.137-.056.355-.235.635-.572a8.18 8.18 0 0 0 .45-.606zm1.64-1.33a12.71 12.71 0 0 1 1.01-.193 11.744 11.744 0 0 1-.51-.858 20.801 20.801 0 0 1-.5 1.05zm2.446.45c.15.163.296.3.435.41.24.19.407.253.498.256a.107.107 0 0 0 .07-.015.307.307 0 0 0 .094-.125.436.436 0 0 0 .059-.2.095.095 0 0 0-.026-.063c-.052-.062-.2-.152-.518-.209a3.876 3.876 0 0 0-.612-.053zM8.078 7.8a6.7 6.7 0 0 0 .2-.828c.031-.188.043-.343.038-.465a.613.613 0 0 0-.032-.198.517.517 0 0 0-.145.04c-.087.035-.158.106-.196.283-.04.192-.03.469.046.822.024.111.054.227.09.346z"/>
                            </svg>
                        </a>
                    {% endif %}
                </td>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                {% if student.birth_date %}
                    <td>{{ student.birth_date }}</td>
                    <td>{{ student.age }}</td>
                {% else %}
                    <td>Undefined</td>
                    <td>Undefined</td>
                {% endif %}
                <td>{{ student.grade }}</td>
                <td>{{ student.group.group_name }}</td>
                <td><a type="button" class="btn btn-warning"
                       href="{% url 'students:update_student' student.pk %}">Edit</a>
                </td>
                <td>
                    <a type="button" class="btn btn-danger"
                       href="{% url 'students:delete_student' student.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}