src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import IndexView, search, Login, Logout, Registration, ActivateUser, ProfileView, ProfileUpdateView

urlpatterns = [
                  path("", IndexView.as_view(), name="index"),
                  path("admin/", admin.site.urls),
                  path("search/", search, name="search"),
                  path("students/", include("students.urls")),
                  path("teachers/", include("teachers.urls")),
                  path("groups/", include("groups.urls")),
                  path("login/", Login.as_view(), name="login"),
                  path("logout/", Logout.as_view(), name="logout"),
                  path("registration/", Registration.as_view(), name="registration"),
                  path("activate/<str:uuid64>/<str:token>", ActivateUser.as_view(), name="activate_user"),
                  path("profile/<int:pk>", ProfileView.as_view(), name="profile"),
                  path("profile/<int:pk>/update", ProfileUpdateView.as_view(), name="profile-update"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/groups/urls.py
from django.urls import path

from groups.views import GroupListView, CreateGroupView, UpdateGroupView, DeleteGroupView

app_name = "groups"

urlpatterns = [
    path("", GroupListView.as_view(), name="get_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
]

src/students/urls.py
from django.urls import path

from students.views import StudentListView, CreateStudentView, UpdateStudentView, DeleteStudentView

app_name = "students"

urlpatterns = [
    path("", StudentListView.as_view(), name="all_students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:pk>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:pk>/", DeleteStudentView.as_view(), name="delete_student"),
]

src/teachers/urls.py
from django.urls import path

from teachers.views import CreateTeacherView, TeacherListView, UpdateTeacherView, DeleteTeacherView

app_name = "teachers"

urlpatterns = [
    path("", TeacherListView.as_view(), name="get_teachers"),
    path("create/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<uuid:pk>/", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<uuid:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/core/models.py
from datetime import datetime
from uuid import uuid4

from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator, MinLengthValidator
from django.db import models
from location_field.models.plain import PlainLocationField
from phonenumber_field.modelfields import PhoneNumberField

from utils import directory_path


class Person(models.Model):
    class Meta:
        abstract = True

    uuid = models.UUIDField(
        primary_key=True,
        editable=False,
        default=uuid4,
        unique=True,
        db_index=True,
    )
    avatar = models.ImageField(
        upload_to=directory_path,
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])],
        null=True,
        blank=True,
        default='')
    first_name = models.CharField(
        max_length=100,
        validators=[
            MinLengthValidator(2),
        ],
        default=''
    )
    last_name = models.CharField(
        max_length=100,
        validators=[
            MinLengthValidator(2),
        ],
        default=''
    )
    email = models.EmailField(max_length=100, default='')
    birth_date = models.DateField(null=True, default='')

    @property
    def get_photo_url(self):
        if self.avatar and hasattr(self.avatar, 'url'):
            return self.avatar.url
        else:
            return "/media/avatar.jpeg"

    def age(self):
        return datetime.now().year - self.birth_date.year


class Profile(models.Model):
    STUDENT = "Student"
    TEACHER = "Teacher"
    MENTOR = "Mentor"
    USER_TYPE_CHOICES = (
        (STUDENT, "Student"),
        (TEACHER, "Teacher"),
        (MENTOR, "Mentor"),
    )

    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    avatar = models.ImageField(
        upload_to=directory_path,
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])],
        null=True,
        blank=True,
        default="/media/avatar.jpeg"
    )
    birth_date = models.DateField(null=True, default='')
    phone_number = PhoneNumberField()
    facebook = models.URLField(max_length=255, null=True, blank=True, default='')
    github = models.URLField(max_length=255, null=True, blank=True, default='')
    city = models.CharField(max_length=255, null=True, blank=True, default='')
    location = PlainLocationField(based_fields=['city'], zoom=7, null=True, blank=True, default='')
    user_type = models.CharField(max_length=50, choices=USER_TYPE_CHOICES)

    @property
    def get_photo_url(self):
        if self.avatar and hasattr(self.avatar, 'url'):
            return self.avatar.url
        else:
            return "/media/avatar.jpeg"

    def __str__(self):
        return f"{self.user.username} {self.user.first_name} {self.user.last_name} {self.user.email}"

src/core/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.forms import ModelForm, DateField, DateInput

from core.models import Profile


class PersonForm(ModelForm):
    birth_date = DateField(
        input_formats=["%d.%m.%Y", "%Y-%m-%d"],
        widget=DateInput(attrs={"placeholder": "dd.mm.yyyy", "type": "date"}),
    )

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email.lower():
            raise ValidationError("Yandex domain is forbidden in our country")

        return email

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean(self):
        cleaned_data = super().clean()

        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]

        if first_name == last_name:
            raise ValidationError("First name and last name can`t be equal")

        return cleaned_data


class RegistrationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ["first_name", "last_name", "username", "email", "password1", "password2"]


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ["avatar", "birth_date", "phone_number", "city", "facebook", "github", "user_type"]

src/core/views.py
from django.contrib.auth import login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.views.generic import TemplateView, CreateView, RedirectView, DetailView, UpdateView

from core.forms import RegistrationForm, ProfileForm
from core.models import Profile
from core.services.emails import send_registration_email
from core.utility.token_generator import TokenGenerator
from students.models import Student


class IndexView(TemplateView):
    template_name = "index.html"


class Registration(CreateView):
    template_name = "registration/create_user.html"
    form_class = RegistrationForm
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_active = False
        self.object.save()

        send_registration_email(
            self.request, user_instance=self.object
        )

        return super().form_valid(form)


class ActivateUser(RedirectView):
    url = reverse_lazy("index")

    def get(self, request, uuid64, token, *args, **kwargs):
        try:
            pk = force_str(urlsafe_base64_decode(uuid64))
            current_user = get_user_model().objects.get(pk=pk)
        except (get_user_model().DoesNotExist, TypeError, ValueError):
            return HttpResponse("Wrong data!")

        if current_user and TokenGenerator().check_token(current_user, token):
            current_user.is_active = True
            current_user.save()
            login(request, current_user)

            return super().get(request, *args, **kwargs)

        return HttpResponse("Wrong data!")


class Login(LoginView):
    next_page = reverse_lazy("index")


class Logout(LogoutView):
    next_page = reverse_lazy("login")


def search(request):
    if request.method == "POST":
        searched = request.POST["searched"]
        students = Student.objects.filter(Q(first_name__contains=searched) | Q(last_name__contains=searched))
        print(students)
        return render(request, template_name="search.html", context={"searched": searched, "students": students})

    return render(request, template_name="search.html", context={})


class ProfileView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = "profile.html"


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = "profile-update.html"
    login_url = "login"

    def get_success_url(self):
        return reverse_lazy('profile', kwargs={'pk': self.kwargs['pk']})

src/core/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cover.css' %}"/>
</head>
<body class="d-flex h-100 text-center text-white bg-dark">

<div class="container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0">LMS</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link" href="{% url "index" %}">Home</a>
                <a class="nav-link" href="{% url "students:all_students" %}">Students</a>
                <a class="nav-link" href="{% url "teachers:get_teachers" %}">Teachers</a>
                <a class="nav-link" href="{% url "groups:get_groups" %}">Groups</a>
                {% if user.is_authenticated %}
                    <div class="nav-link d-block flex-shrink-0 dropdown">
                        <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" id="dropdownUser2"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ user.profile.get_photo_url }}" alt="mdo" width="32" height="32"
                                 class="rounded-circle">
                        </a>
                        <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
                            <li><a class="dropdown-item fw-bold" href="">{{ user.username | title }}</a></li>
                            <li><a class="dropdown-item" href="{% url 'profile' user.profile.pk %}">Profile</a></li>
                            {% if user.is_staff %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin page</a></li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Change password</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Sign out</a></li>
                        </ul>
                    </div>
                {% else %}
                    <div class="nav-link d-block flex-shrink-0 dropdown">
                        <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" id="dropdownUser2"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="/media/avatar.jpeg" alt="mdo" width="32" height="32" class="rounded-circle">
                        </a>
                        <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
                            <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                            <li><a class="dropdown-item" href="{% url 'registration' %}">Registration</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Reset password</a></li>
                            {#                        <li><a class="dropdown-item" href="#">Sign out</a></li>#}
                        </ul>
                    </div>
                {% endif %}
            </nav>
        </div>
    </header>

    <main class="px-3">
        {% block content %}

        {% endblock %}
    </main>

    <footer class="mt-auto text-white-50">
        Created by Nekipielov Dmytro
    </footer>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

src/core/templates/create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Create
{% endblock %}

{% block content %}
    <div>
        <form method="POST" enctype="multipart/form-data" style="width: 25em; align-content: center; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create" style="margin: 10px;">Create
            </button>
        </form>
    </div>
{% endblock content %}

src/core/templates/delete.html
{% extends "index.html" %}

{% block title %}
    Students
{% endblock %}

{% block content %}
    <form method="POST">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" class="btn btn-danger" value="Confirm"/>
        <input type="button" class="btn btn-secondary" onClick="history.go(-1);" value="Cancel"/>
    </form>
{% endblock content %}

src/core/templates/index.html
{% extends "base.html" %}

{% block title %}
    Home page
{% endblock %}

{% block content %}
    <div class="container text-center w-25">
        <img src="https://images.kinorium.com/movie/shot/573253/w1500_48908865.jpg" alt="Django unchained"
             class="img-fluid">
    </div>
{% endblock %}

src/core/templates/profile-update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Update information
{% endblock %}

{% block content %}
    <div>
        <form method="POST" enctype="multipart/form-data" style="width: 25em; align-content: center; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create" style="margin-top: 20px;">Save</button>
            <button type="button" class="btn btn-secondary" onClick="history.go(-1);" value="Cancel"
                    style="margin-top: 20px;">Cancel
            </button>
        </form>
    </div>
{% endblock content %}

src/core/templates/profile.html
{% extends "index.html" %}

{% block title %}
    Profile
{% endblock %}

{% block content %}

    <div class="container">
        <div class="main-body">
            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="{{ user.profile.get_photo_url }}" alt="avatar"
                                     class="rounded float-left" width="150">
                                <div class="mt-3 text-dark">
                                    <h4>{{ user.username }}</h4>
                                    <p class="text-secondary mb-1">{{ user.profile.user_type }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if user.profile.github or user.profile.facebook %}
                        <div class="card mt-3">

                            <ul class="list-group list-group-flush">
                                {% if user.profile.github %}
                                    <a class="text-decoration-none text-reset" href="{{ user.profile.github }}"
                                       target="_blank">
                                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                            <h6 class="mb-0">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                     viewBox="0 0 24 24"
                                                     fill="none" stroke="currentColor" stroke-width="2"
                                                     stroke-linecap="round"
                                                     stroke-linejoin="round"
                                                     class="feather feather-github mr-2 icon-inline">
                                                    <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
                                                </svg>
                                                Github
                                            </h6>
                                            {#                                    <span class="text-secondary">bootdey</span>#}
                                        </li>
                                    </a>
                                {% endif %}
                                {% if user.profile.facebook %}
                                    <a class="text-decoration-none text-reset" href="{{ user.profile.facebook }}"
                                       target="_blank">
                                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                            <h6 class="mb-0">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                     viewBox="0 0 24 24"
                                                     fill="none" stroke="currentColor" stroke-width="2"
                                                     stroke-linecap="round"
                                                     stroke-linejoin="round"
                                                     class="feather feather-facebook mr-2 icon-inline text-primary">
                                                    <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path>
                                                </svg>
                                                Facebook
                                            </h6>
                                            {#                                    <span class="text-secondary">bootdey</span>#}
                                        </li>
                                    </a>
                                {% endif %}
                            </ul>
                        </div>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0 text-secondary">Name</h6>
                                </div>
                                <div class="col-sm-9 text-dark">
                                    {{ user.first_name }}
                                </div>
                                <div class="col-sm-3">
                                    <h6 class="mb-0 text-secondary">Surname</h6>
                                </div>
                                <div class="col-sm-9 text-dark">
                                    {{ user.last_name }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0 text-secondary">Email</h6>
                                </div>
                                <div class="col-sm-9 text-dark">
                                    {{ user.email }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0 text-secondary">Phone</h6>
                                </div>
                                <div class="col-sm-9 text-dark">
                                    {{ user.profile.phone_number }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0 text-secondary">City</h6>
                                </div>
                                <div class="col-sm-9 text-dark">
                                    {{ user.profile.city }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-12">
                                    <a class="btn btn-warning"
                                       href="{% url 'profile-update' user.profile.id %}">Edit</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

src/core/templates/search.html
{% extends "index.html" %}

{% block title %}
    Search results
{% endblock %}

{% block content %}
    <div>
        {% if searched %}
            <h4>What was found on request "{{ searched }}"</h4>
            {% for student in students %}
                <a href="{% url "students:update_student" student.pk %}"> {{ student }}</a><br>
            {% endfor %}
        {% else %}
            You forgot to search
        {% endif %}
    </div>
{% endblock content %}

src/core/templates/update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Update information
{% endblock %}

{% block content %}
    <div>
        <form method="POST" enctype="multipart/form-data" style="width: 25em; align-content: center; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create" style="margin-top: 20px;">Save</button>
            <button type="button" class="btn btn-secondary" onClick="history.go(-1);" value="Cancel"
                    style="margin-top: 20px;">Cancel
            </button>
        </form>
    </div>
{% endblock content %}